from web1.views.aluno_view import *
from comprovante_pdf_view import *
from web1.views.curso_view import *
from web1.views.exclusoes_view import *
from web1.views.funcionario_view import *
from web1.views.listagens_view import *
from web1.views.login_verifica_grupo import *
from web1.views.permissao_view import *
from web1.views.tipo_oferta import *
from web1.views.tipo_permissao import *
from web1.views.turma_view import *
from web1.views.validacoes_view import *
